In [1]:
print("hello world")

hello world

In [2]:
# import pandas library
import pandas as pd

In [6]:
from sklearn.datasets import load_digits

digits = load_digits()

print("Dataset loaded successfully!")
print("Data shape:", digits.data.shape)
print("Image shape:", digits.images.shape)
print("Target shape:", digits.target.shape)
print("First 10 labels:", digits.target[:10])

Dataset loaded successfully!
Data shape: (1797, 64)
Image shape: (1797, 8, 8)
Target shape: (1797,)
First 10 labels: [0 1 2 3 4 5 6 7 8 9]

In [1]:
import numpy as np

In [1]:
import pandas as pd

In [2]:
#read data from csv file
df = pd.read_csv('data.csv')

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
import pandas as pd

df = pd.read_csv("data.csv")
df.to_excel("data.xlsx", index=False)   # index=False দিলে বাড়তি সিরিয়াল কলাম আসবে না

df2 = pd.read_excel("data.xlsx")
print(df2.head())

   id     name   age     class  gender        city  marks passed
0   1    Rahim  15.0   Class 9    Male       Dhaka   78.0    Yes
1   2    Karim  16.0  Class 10    Male  Chattogram   65.0    Yes
2   3  Sumaiya  15.0   Class 9  Female       Dhaka   88.0    Yes
3   4   Nusrat  17.0  Class 11  Female    Rajshahi   92.0    Yes
4   5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No

In [1]:
import pandas as pd

df = pd.read_csv("data.csv")

# JSON
df.to_json("data.json", orient="records", indent=2)
df_json = pd.read_json("data.json")
print(df_json.head())

# Parquet
df.to_parquet("data.parquet", index=False)
df_parquet = pd.read_parquet("data.parquet")
print(df_parquet.head())

   id     name   age     class  gender        city  marks passed
0   1    Rahim  15.0   Class 9    Male       Dhaka   78.0    Yes
1   2    Karim  16.0  Class 10    Male  Chattogram   65.0    Yes
2   3  Sumaiya  15.0   Class 9  Female       Dhaka   88.0    Yes
3   4   Nusrat  17.0  Class 11  Female    Rajshahi   92.0    Yes
4   5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No
   id     name   age     class  gender        city  marks passed
0   1    Rahim  15.0   Class 9    Male       Dhaka   78.0    Yes
1   2    Karim  16.0  Class 10    Male  Chattogram   65.0    Yes
2   3  Sumaiya  15.0   Class 9  Female       Dhaka   88.0    Yes
3   4   Nusrat  17.0  Class 11  Female    Rajshahi   92.0    Yes
4   5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No

In [2]:
# create dataframe from dictionary of lists
data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 25, 30]
}
df = pd.DataFrame(data)

In [4]:
df.head()

  Name  Age
0    A   20
1    B   25
2    C   30

In [5]:
# each dict = one row
data = [
    {"Name": "A", "Age": 20},
    {"Name": "B", "Age": 25}
]
df = pd.DataFrame(data)

In [6]:
df.head()

  Name  Age
0    A   20
1    B   25

In [7]:
# define column names separately
data = [
    ["A", 20],
    ["B", 25]
]
df = pd.DataFrame(data, columns=["Name", "Age"])

In [8]:
df.head()

  Name  Age
0    A   20
1    B   25

In [9]:
df = pd.read_csv('data.csv')

In [10]:
# show first 5 rows (default)
df.head()

   id     name   age     class  gender        city  marks passed
0   1    Rahim  15.0   Class 9    Male       Dhaka   78.0    Yes
1   2    Karim  16.0  Class 10    Male  Chattogram   65.0    Yes
2   3  Sumaiya  15.0   Class 9  Female       Dhaka   88.0    Yes
3   4   Nusrat  17.0  Class 11  Female    Rajshahi   92.0    Yes
4   5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No

In [11]:
# show first 10 rows
df.head(10)

   id     name   age     class  gender        city  marks passed
0   1    Rahim  15.0   Class 9    Male       Dhaka   78.0    Yes
1   2    Karim  16.0  Class 10    Male  Chattogram   65.0    Yes
2   3  Sumaiya  15.0   Class 9  Female       Dhaka   88.0    Yes
3   4   Nusrat  17.0  Class 11  Female    Rajshahi   92.0    Yes
4   5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No
5   6      Mim  15.0   Class 9  Female      Sylhet    NaN    Yes
6   7     Arif  17.0  Class 11    Male       Dhaka   55.0    Yes
7   8    Sadia  16.0  Class 10  Female  Chattogram   72.0    Yes
8   9    Imran   NaN  Class 10    Male    Rajshahi   38.0     No
9  10  Farhana  15.0   Class 9  Female      Khulna   81.0    Yes

In [12]:
# show last 5 rows
df.tail()

    id     name   age     class  gender        city  marks passed
26  27    Mahin  16.0  Class 10    Male      Khulna    NaN     No
27  28     Rima  15.0   Class 9  Female       Dhaka   79.0    Yes
28  29    Fahim  17.0  Class 11    Male  Chattogram   64.0    Yes
29  30  Sraboni  16.0  Class 10  Female    Rajshahi   86.0    Yes
30   5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No

In [13]:
# randomly sample 5 rows
df.sample(5)

    id    name   age     class  gender    city  marks passed
10  11  Shakil  17.0  Class 11    Male  Sylhet   60.0    Yes
24  25  Sabbir  15.0   Class 9    Male  Sylhet   58.0    Yes
18  19  Nayeem  15.0   Class 9    Male   Dhaka   69.0    Yes
4    5  Tanvir  16.0  Class 10    Male  Khulna   38.0     No
5    6     Mim  15.0   Class 9  Female  Sylhet    NaN    Yes

In [15]:
# get number of rows and columns
df.shape

(31, 8)

In [16]:
# get total no of element (rowsxcols)
df.size

248

In [17]:
# list of column names
df.columns

Index(['id', 'name', 'age', 'class', 'gender', 'city', 'marks', 'passed'], dtype='object')

In [18]:
# data type of each column
df.dtypes

id          int64
name       object
age       float64
class      object
gender     object
city       object
marks     float64
passed     object
dtype: object

In [19]:
# summary of dataframe (non-null count, dtypes)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      31 non-null     int64
 1   name    31 non-null     object
 2   age     30 non-null     float64
 3   class   31 non-null     object
 4   gender  31 non-null     object
 5   city    30 non-null     object
 6   marks   28 non-null     float64
 7   passed  31 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 2.1+ KB

In [20]:
# summary statistics for numerical columns
df.describe()

              id        age      marks
count  31.000000  30.000000  28.000000
mean   15.161290  15.966667  67.107143
std     8.858505   0.808717  19.911544
min     1.000000  15.000000  33.000000
25%     7.500000  15.000000  54.250000
50%    15.000000  16.000000  71.000000
75%    22.500000  17.000000  83.250000
max    30.000000  17.000000  95.000000

In [22]:
 #7. Value Counts (Very Useful)
# count unique values in a column
df["gender"].value_counts()

gender
Male      16
Female    15
Name: count, dtype: int64

In [28]:
df["gender"].value_counts(normalize=True)  # percentage of each unique value

gender
Male      0.516129
Female    0.483871
Name: proportion, dtype: float64

In [29]:
#Unique values in a column
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [30]:
#Unique values in a column
df["gender"].nunique()

2

🔹 9. Sorting Data

In [33]:
# sort by one column
df.sort_values(by="age")

    id     name   age     class  gender        city  marks passed
0    1    Rahim  15.0   Class 9    Male       Dhaka   78.0    Yes
2    3  Sumaiya  15.0   Class 9  Female       Dhaka   88.0    Yes
5    6      Mim  15.0   Class 9  Female      Sylhet    NaN    Yes
9   10  Farhana  15.0   Class 9  Female      Khulna   81.0    Yes
12  13     Rafi  15.0   Class 9    Male  Chattogram   33.0     No
15  16    Lamia  15.0   Class 9  Female    Rajshahi   84.0    Yes
21  22     Ritu  15.0   Class 9  Female      Khulna   74.0    Yes
18  19   Nayeem  15.0   Class 9    Male       Dhaka   69.0    Yes
27  28     Rima  15.0   Class 9  Female       Dhaka   79.0    Yes
24  25   Sabbir  15.0   Class 9    Male      Sylhet   58.0    Yes
4    5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No
23  24    Anika  16.0  Class 10  Female  Chattogram   91.0    Yes
14  15    Hasan  16.0  Class 10    Male         NaN   70.0    Yes
11  12    Tania  16.0  Class 10  Female       Dhaka    NaN    Yes
7    8    Sadia  16.0  Class 10  Female  Chattogram   72.0    Yes
1    2    Karim  16.0  Class 10    Male  Chattogram   65.0    Yes
30   5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No
29  30  Sraboni  16.0  Class 10  Female    Rajshahi   86.0    Yes
26  27    Mahin  16.0  Class 10    Male      Khulna    NaN     No
17  18    Priya  16.0  Class 10  Female      Sylhet   77.0    Yes
20  21     Rony  16.0  Class 10    Male       Dhaka   52.0    Yes
3    4   Nusrat  17.0  Class 11  Female    Rajshahi   92.0    Yes
10  11   Shakil  17.0  Class 11    Male      Sylhet   60.0    Yes
6    7     Arif  17.0  Class 11    Male       Dhaka   55.0    Yes
16  17    Sohel  17.0  Class 11    Male      Khulna   34.0     No
13  14   Jannat  17.0  Class 11  Female       Dhaka   95.0    Yes
22  23  Jubayer  17.0  Class 11    Male    Rajshahi   36.0     No
19  20      Mou  17.0  Class 11  Female  Chattogram   89.0    Yes
28  29    Fahim  17.0  Class 11    Male  Chattogram   64.0    Yes
25  26   Tasnim  17.0  Class 11  Female       Dhaka   83.0    Yes
8    9    Imran   NaN  Class 10    Male    Rajshahi   38.0     No

In [34]:
# sort in descending order
df.sort_values(by="age", ascending=False)

    id     name   age     class  gender        city  marks passed
3    4   Nusrat  17.0  Class 11  Female    Rajshahi   92.0    Yes
6    7     Arif  17.0  Class 11    Male       Dhaka   55.0    Yes
10  11   Shakil  17.0  Class 11    Male      Sylhet   60.0    Yes
13  14   Jannat  17.0  Class 11  Female       Dhaka   95.0    Yes
19  20      Mou  17.0  Class 11  Female  Chattogram   89.0    Yes
16  17    Sohel  17.0  Class 11    Male      Khulna   34.0     No
25  26   Tasnim  17.0  Class 11  Female       Dhaka   83.0    Yes
22  23  Jubayer  17.0  Class 11    Male    Rajshahi   36.0     No
28  29    Fahim  17.0  Class 11    Male  Chattogram   64.0    Yes
7    8    Sadia  16.0  Class 10  Female  Chattogram   72.0    Yes
14  15    Hasan  16.0  Class 10    Male         NaN   70.0    Yes
11  12    Tania  16.0  Class 10  Female       Dhaka    NaN    Yes
4    5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No
1    2    Karim  16.0  Class 10    Male  Chattogram   65.0    Yes
30   5   Tanvir  16.0  Class 10    Male      Khulna   38.0     No
29  30  Sraboni  16.0  Class 10  Female    Rajshahi   86.0    Yes
23  24    Anika  16.0  Class 10  Female  Chattogram   91.0    Yes
17  18    Priya  16.0  Class 10  Female      Sylhet   77.0    Yes
20  21     Rony  16.0  Class 10    Male       Dhaka   52.0    Yes
26  27    Mahin  16.0  Class 10    Male      Khulna    NaN     No
0    1    Rahim  15.0   Class 9    Male       Dhaka   78.0    Yes
5    6      Mim  15.0   Class 9  Female      Sylhet    NaN    Yes
12  13     Rafi  15.0   Class 9    Male  Chattogram   33.0     No
9   10  Farhana  15.0   Class 9  Female      Khulna   81.0    Yes
2    3  Sumaiya  15.0   Class 9  Female       Dhaka   88.0    Yes
15  16    Lamia  15.0   Class 9  Female    Rajshahi   84.0    Yes
21  22     Ritu  15.0   Class 9  Female      Khulna   74.0    Yes
18  19   Nayeem  15.0   Class 9    Male       Dhaka   69.0    Yes
24  25   Sabbir  15.0   Class 9    Male      Sylhet   58.0    Yes
27  28     Rima  15.0   Class 9  Female       Dhaka   79.0    Yes
8    9    Imran   NaN  Class 10    Male    Rajshahi   38.0     No

 10. Reset Index

In [36]:
# reset index after filtering/sorting
df.reset_index(drop=True, inplace=True)

In [37]:
# rename columns
df.rename(columns={"gender": "Sex", "marks": "Passenger_Class"}, inplace=True)

In [38]:
df.head(5)

   id     name   age     class     Sex        city  Passenger_Class passed
0   1    Rahim  15.0   Class 9    Male       Dhaka             78.0    Yes
1   2    Karim  16.0  Class 10    Male  Chattogram             65.0    Yes
2   3  Sumaiya  15.0   Class 9  Female       Dhaka             88.0    Yes
3   4   Nusrat  17.0  Class 11  Female    Rajshahi             92.0    Yes
4   5   Tanvir  16.0  Class 10    Male      Khulna             38.0     No

In [39]:
# 12. Quick Checks
# check if any missing values exist
df.isnull().sum()

id                 0
name               0
age                1
class              0
Sex                0
city               1
Passenger_Class    3
passed             0
dtype: int64

In [40]:
# check duplicates
df.duplicated().sum()

np.int64(1)

In [41]:
#13. Export Data
# save to CSV
df.to_csv("output.csv", index=False)

# save to Excel
df.to_excel("output.xlsx", index=False)